/**
 * PhotosynQ Project
 * Available Helper functions as a node package
 */

module.exports.ArrayNth = require('./src/ArrayNth');
module.exports.ArrayRange = require('./src/ArrayRange');
module.exports.ArrayUnZip = require('./src/ArrayUnZip');
module.exports.ArrayZip = require('./src/ArrayZip');
module.exports.GetIndexByLabel = require('./src/GetIndexByLabel');
module.exports.GetLabelLookup = require('./src/GetLabelLookup');
module.exports.GetProtocolByLabel = require('./src/GetProtocolByLabel');
module.exports.MathLINREG = require('./src/MathLINREG');
module.exports.MathLN = require('./src/MathLN');
module.exports.MathLOG = require('./src/MathLOG');
module.exports.MathMAX = require('./src/MathMAX');
module.exports.MathMEAN = require('./src/MathMEAN');
module.exports.MathMEDIAN = require('./src/MathMEDIAN');
module.exports.MathMIN = require('./src/MathMIN');
module.exports.MathROUND = require('./src/MathROUND');
module.exports.MathSTDERR = require('./src/MathSTDERR');
module.exports.MathSTDEV = require('./src/MathSTDEV');
module.exports.MathSTDEVS = require('./src/MathSTDEVS');
module.exports.MathSUM = require('./src/MathSUM');
module.exports.MathVARIANCE = require('./src/MathVARIANCE');
module.exports.info = require('./src/Message').info;
module.exports.warning = require('./src/Message').warning;
module.exports.danger = require('./src/Message').danger;
module.exports.NonLinearRegression = require('./src/NonLinearRegression');
module.exports.TransformTrace = require('./src/TransformTrace');
module.exports.MathMULTREG = require('./src/additional_functions').MathMULTREG;
module.exports.MathEXPINVREG = require('./src/additional_functions').MathEXPINVREG;
module.exports.MathPOLYREG = require('./src/additional_functions').MathPOLYREG;
module.exports.subVV = require('./src/additional_functions').subVV;
module.exports.proj = require('./src/additional_functions').proj;
module.exports.innerProd = require('./src/additional_functions').innerProd;
module.exports.normal = require('./src/additional_functions').normal;
module.exports.QRDecomp = require('./src/additional_functions').QRDecomp;
module.exports.transpose = require('./src/additional_functions').transpose;
module.exports._getCol = require('./src/additional_functions')._getCol;
module.exports.dotVV = require('./src/additional_functions').dotVV;
module.exports.dotMMbig = require('./src/additional_functions').dotMMbig;
module.exports._dim = require('./src/additional_functions')._dim;
module.exports.dim = require('./src/additional_functions').dim;
module.exports.clone = require('./src/additional_functions').clone;
module.exports.diag = require('./src/additional_functions').diag;
module.exports.rep = require('./src/additional_functions').rep;
module.exports.identity = require('./src/additional_functions').identity;
module.exports.inv = require('./src/additional_functions').inv;
module.exports.dotMV = require('./src/additional_functions').dotMV;
module.exports.dotVM = require('./src/additional_functions').dotVM;
module.exports.dotMMsmall = require('./src/additional_functions').dotMMsmall;
module.exports.mulVS = require('./src/additional_functions').mulVS;
module.exports.mulSV = require('./src/additional_functions').mulSV;
module.exports.dot = require('./src/additional_functions').dot;